#!/usr/bin/env bash
# One-shot helper: opens the 25 Operator Lens issues via the GitHub CLI.
#
# The 19 items from docs/operator-lens/PLAN.md section 6, plus 6 defects and
# gaps found while building the module.
#
# Requires the GitHub CLI, authenticated:
#   winget install --id GitHub.cli
#   gh auth login
#
# Run from the repo root:
#   bash scripts/open-issues.sh
#
# Safe to read before running; it only calls `gh issue create`. It is NOT
# idempotent: running it twice creates duplicates.

set -euo pipefail

command -v gh >/dev/null || { echo "gh not found. Install the GitHub CLI first."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated. Run: gh auth login"; exit 1; }

created=0

open_issue () {
  local title="$1" body="$2"
  local url
  url="$(gh issue create --title "$title" --body "$body")"
  created=$((created + 1))
  printf '%-4s %s\n     %s\n' "[$created]" "$title" "$url"
}

# ---------------------------------------------------------------------------
# Deferred features (PLAN.md section 6)
# ---------------------------------------------------------------------------

open_issue "Extraction accuracy: multi-column layouts and footnoted figures" \
"Deferred feature, from docs/operator-lens/PLAN.md section 6 (item 1).

Model extraction is not built at all yet, and when it is, multi-column
statement layouts and footnoted figures are the known failure cases called out
in SPEC section 10.

Today the only working input is the Operator Lens input workbook."

open_issue "Balance sheet support and cross-statement coherence rules" \
"Deferred feature, from PLAN.md section 6 (item 2).

v1 is income statement only. SPEC section 10 notes this removes the strongest
coherence checks: receivables against revenue, and inventory turns."

open_issue "Cash flow statement support" \
"Deferred feature, from PLAN.md section 6 (item 3).

Out of scope for v1 alongside the balance sheet."

open_issue "Real auth (Phase 3): replace the Demo User stub" \
"Deferred feature, from PLAN.md section 6 (item 4).

The shell runs as a static Demo User with admin rights.
\`requireProjectAccess\` and \`requireCurrentUser\` in
packages/server/src/access-service.ts always grant. Spots that need real
identity are marked PHASE-3.

Affected columns are plain strings today: \`createdByName\`,
\`figuresConfirmedByName\`, \`ownerName\`."

open_issue "Roles, permissions and admin console" \
"Deferred feature, from PLAN.md section 6 (item 5).

Follows real auth. Engagements are separated by project, not by person."

open_issue "Export to XLSX, PPTX, PDF and JSON" \
"Deferred feature, from PLAN.md section 6 (item 6).

CSV export is built (SPEC section 8.7, byte-identical on repeat). Other formats
are explicitly out of scope for v1."

open_issue "File versioning and preview" \
"Deferred feature, from PLAN.md section 6 (item 7).

The uploaded workbook is not retained. \`SourceDocument.storagePath\` records
\`upload://<filename>\` as a note of what was read, not a location, so
re-extraction from the original file is impossible."

open_issue "Operator-tunable thresholds, versioned per engagement" \
"Deferred feature, from PLAN.md section 6 (item 8).

Thresholds are fixed in lib/ruleset.ts and compared as integer basis points.
Making them tunable interacts with the determinism contract: any change needs a
new \`rulesetVersion\` so an old engagement still reproduces what it said."

open_issue "Operator-supplied peer set as a benchmark override" \
"Deferred feature, from PLAN.md section 6 (item 9).

Benchmarks are a seeded snapshot and cannot be overridden per engagement."

open_issue "Portfolio view across companies" \
"Deferred feature, from PLAN.md section 6 (item 10).

Single company per engagement, no cross-company comparison."

open_issue "Multi-currency support" \
"Deferred feature, from PLAN.md section 6 (item 11).

USD only, no conversion. \`Engagement.currency\` exists and is carried through
to the export, but nothing converts."

open_issue "Benchmark refresh pipeline and set-versioning UI" \
"Deferred feature, from PLAN.md section 6 (item 12).

Benchmarks are regenerated by hand:

    py scripts/analysis/build_benchmarks.py

reading scripts/analysis/sources/consumer_retail_peers_v1.csv and writing
packages/db/prisma/benchmarks.v1.json. There is no UI, no refresh schedule, and
no way to see or pick a set version.

Related: nothing currently prevents re-analysing an old engagement against a
newer benchmark set, even though the version is stamped."

open_issue "Column-mapping screen so operators can upload their own layout" \
"Deferred feature, from PLAN.md section 6 (item 13).

lib/parse-workbook.ts reads by the machine codes in column A, so only the
Operator Lens input workbook parses. Any other layout needs mapping."

# ---------------------------------------------------------------------------
# Platform migration (PLAN.md section 6)
# ---------------------------------------------------------------------------

open_issue "Add OPERATOR_LENS to the real PlatformModule Postgres enum" \
"Platform migration, from PLAN.md section 6 (item 14).

This template has no \`PlatformModule\` enum because SQLite has no Prisma
enums, so module enablement here is static seed data. The UPPER_SNAKE value is
added only when the module lands on the real platform."

open_issue "Convert String status columns to platform Prisma enums" \
"Platform migration, from PLAN.md section 6 (item 15).

SQLite has no Prisma enums, so these are \`String\` columns guarded by
TypeScript unions and marked PHASE-3 in packages/db/prisma/schema.prisma:

- \`Engagement.status\`, \`Engagement.unitScale\`
- \`SourceDocument.sourceKind\`, \`SourceDocument.extractionStatus\`
- \`Flag.axis\`, \`Flag.severity\`, \`Flag.status\`"

open_issue "Follow the platform INTEGRATION-PLAYBOOK when landing the module" \
"Platform migration, from PLAN.md section 6 (item 16).

Auth, audit and AI wiring come from the platform through \`@ssa/server\` and
\`@ssa/ai-client\`."

# ---------------------------------------------------------------------------
# Known risks (PLAN.md section 6)
# ---------------------------------------------------------------------------

open_issue "Benchmark source licensing and provenance for client-facing use" \
"Known risk, from PLAN.md section 6 (item 17).

The seeded set is built from SEC EDGAR XBRL company facts, which is public
data. Confirm what may be shown to a client, and how the peer set must be
attributed, before any of this reaches a client deliverable.

Every figure traces to a filing via
scripts/analysis/sources/consumer_retail_peers_v1.csv, which records the XBRL
concept name and filing URL per company."

open_issue "Industry taxonomy choice (NAICS vs SIC vs internal) and benchmark join effects" \
"Known risk, from PLAN.md section 6 (item 18).

The taxonomy is provisional and internal, not NAICS or SIC. It is stated as an
assumption on the Reference sheet of the input workbook. Changing it changes
every benchmark join, so it needs deciding before the benchmark set grows."

open_issue "Stack conflict: tRPC mandated but the template ships route handlers" \
"Known risk, from PLAN.md section 6 (item 19).

Confirm with the engagement lead. The shell ships Next.js route handlers under
apps/shell/src/app/api, and CLAUDE.md states there is no tRPC. Rebuilding that
layer would mean fighting the shell for no user-visible gain.

The second forced deviation is that this is a project-scoped module rather than
a standalone app, which is a net win: per-project gating comes from the shell."

# ---------------------------------------------------------------------------
# Found while building
# ---------------------------------------------------------------------------

open_issue "xlsx package has two unfixed high-severity advisories" \
"Defect found while building.

\`xlsx@0.18.5\` in apps/shell/package.json carries two high-severity advisories
on the npm registry, with no patched version published there because SheetJS
moved distribution to its own CDN:

- Prototype pollution
- Regular expression denial of service (ReDoS)

Low risk today, because the only input is a committed fixture workbook. It
matters before real upload traffic: parsing operator-supplied files is the
module's whole purpose, and the upload route already accepts arbitrary .xlsx.

Options: pull the SheetJS CDN build, pin a different reader, or parse the
workbook without a general-purpose xlsx library."

open_issue "No route-handler or component test coverage" \
"Gap found while building.

All 77 tests are pure lib/ logic: engine, determinism, validate, scorecard,
to-csv, plus Sample Tracker's sort. Untested:

- every route handler under apps/shell/src/app/api/apps/operator-lens
- every component under apps/shell/src/apps/operator-lens/components

This matches Sample Tracker, which has no route or component tests either, so
it is a repo-wide convention rather than an Operator Lens omission. Worth
deciding before more routes land. The upload POST is the highest-value target:
its validation paths were verified by hand with curl, not by a committed test."

open_issue "Review and Confirm gate is specified but not enforced" \
"Defect found while building. This is the most significant gap in the module.

SPEC section 3 makes a human Review and Confirm step mandatory between
extraction and analysis, and states that no route may bypass it. The screen
does not exist.

Both paths that create an engagement set the confirmation fields themselves:

- apps/shell/prisma/seed.ts sets \`figuresConfirmedAt\` directly
- the upload POST in
  apps/shell/src/app/api/apps/operator-lens/projects/[projectSlug]/engagements/route.ts
  sets \`figuresConfirmedAt\` and \`figuresConfirmedByName\` at upload time

So nothing today enforces that a human saw a figure before it was analysed. It
is defensible for a workbook the operator filled in themselves, and no route
bypasses the gate only because there is no other ingestion path yet. It stops
being defensible the moment model extraction lands, because that is exactly the
risk the gate exists to catch: a misread figure flowing silently into a finding
a consultant repeats to a client.

Build the editable review grid (SPEC section 8.3) and make confirmation an
explicit operator action before extraction ships."

open_issue "gapText is presentation data stored in engine output" \
"Defect found while building.

lib/engine.ts writes a \`gapText\` field (for example \`\"541bps\"\`) into a
flag's \`computedValues\` JSON, duplicating its \`gapBps\` sibling in
pre-formatted form.

Consequences:

- the findings UI filters \`*Text\` keys out at render time to avoid showing a
  redundant row, which is a display-layer workaround for a data problem
- the CSV export ships stored JSON verbatim, so \`gapText\` appears in the
  \`computed_values_json\` column

Remove it from the engine and reseed. \`computedValues\` should hold the figures
a rule used, not strings formatted for a screen."

open_issue "Only one benchmark industry and size band is seeded" \
"Gap found while building.

\`consumer-retail-v1\` covers exactly one combination: \`CONSUMER_RETAIL\` at
\`\$25M - \$100M\`, in USD, as of 2026-02-01, sample size 8. Any other
combination gets trend and coherence flags only, reported as unbenchmarked
rather than as a pass.

The upload screen populates its dropdowns from the distinct values in
\`BenchmarkStat\`, so an operator cannot select a combination with no data.
That is correct behaviour, but it currently means one choice each.

Related and worth recording: the peer set runs \$270M to \$565M in revenue
against a \$38.2M demo subject, 7x to 15x larger. They are joined on the
\`\$25M - \$100M\` band because otherwise nothing matches and the benchmark
rules never evaluate, so that band label is a convenience rather than a size
match. The mismatch is written into the benchmark \`source\` string so it
renders on screen. Genuinely \$38M US-listed specialty retailers have largely
been delisted or acquired, so real size-matched comparables need private
company data."

open_issue "reset.sh has the Windows path bug that was fixed in run.sh" \
"Defect found while building.

scripts/reset.sh line 5 uses bare \`pwd\`:

    REPO=\"\$(cd \"\$(dirname \"\${BASH_SOURCE[0]}\")/..\" && pwd)\"
    export DATABASE_URL=\"\${DATABASE_URL:-file:\$REPO/dev.db}\"

Under Git Bash on Windows \`pwd\` returns \`/c/Users/...\`, which Prisma
resolves literally against the drive root and silently creates a phantom
\`C:\\\\c\\\\Users\\\\...\\\\dev.db\` instead of using the repo's database. The
symptom is a reset that appears to succeed while the running app reads a
different file.

scripts/run.sh was fixed for this: it derives a native path with
\`pwd -W\` and falls back to \`\$REPO\` on Linux and macOS. Apply the same fix
to reset.sh.

Note: scripts/reset.ps1 is NOT affected. It converts backslashes correctly,
the same way run.ps1 does, and is the tested Windows path."

echo
echo "Created $created issue(s)."
